#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


VER="161942/957955/version/7/file/ezpublish5_community_project-2014.11.1-gpl-full.tar.gz"
URL="https://ezplatform.com/content/download/208/file/ezplatform-1.9.1.tar.bz2"

cd /usr/local/src
curl -L -f -O $URL
