#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


VER="dist-1.7.4"
URL="https://ezplatform.com/content/download/208/file/ezplatform-$VER.tar.bz2"

SRC="/usr/local/src"
dl $URL $SRC
