#!/bin/sh -ex

DB_NAME=ezplatform
DB_USER=ezplatform
DB_PASS=$(mcookie)

ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/ezplatform

# tweak apache-credit
CONF=/etc/apache2/mods-available/substitute.conf
sed -i "s|</body>|</footer>|g" $CONF

cd $WEBROOT

# php.ini tweaks
PHPINI=/etc/php/7.0/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" /etc/php/7.0/cli/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"America/Los_Angeles\"|" $PHPINI

touch $WEBROOT/app/config/parameters.yml
cat >$WEBROOT/app/config/parameters.yml<<EOF
parameters:
    secret: TURNKEY_SECRET
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: $DB_NAME
    database_user: $DB_USER
    database_password: $DB_PASS
EOF

# configure apache
a2dissite 000-default
a2ensite ezplatform
a2enmod rewrite

# start services
service mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS';"

# make temp swap file to work around limitations of building on system with low RAM
dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
mkswap /var/swap.1
swapon /var/swap.1

COMPOSER_MEMORY_LIMIT=-1 composer install

php -d memory_limit=-1 /var/www/ezplatform/app/console ezplatform:install --env prod clean
composer run-script post-install-cmd

rm -rf app/logs/* app/cache/*
chown -R www-data:www-data app/cache app/logs web

# stop services
service mysql stop

# remove temp swap file
swapoff /var/swap.1
rm -rf /var/swap.1
