#!/bin/bash -e

. /etc/default/inithooks

# Reset APP_SECRET
PASSWORD=$(mcookie)
CONF="/var/www/ibexa/.env"
sed -i "s|APP_SECRET=.*|APP_SECRET=$PASSWORD|" $CONF

# Reset DB password
PASSWORD=$(mcookie)
sed -i "s|DATABASE_URL=\"mysql:\/\/ibexa:.*\"|DATABASE_URL=\"mysql:\/\/ibexa:$PASSWORD@localhost:3306/ibexa?appVersion=15\"|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ibexa --pass="$PASSWORD"
