#!/bin/bash -e

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF="/var/www/ezplatform/app/config/parameters.yml"
sed -i "s|secret: .*|secret: $PASSWORD|" $CONF
sed -i "s|database_password: .*|database_password: $PASSWORD|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ezplatform --pass="$PASSWORD"

