#!/bin/bash -e
# regenerate ezpublish mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/var/www/ezpublish/ezpublish_legacy/settings/siteaccess/eng/site.ini.append.php
sed -i "s|Password=.*|Password=$PASSWORD|" $CONF

CONF=/var/www/ezpublish/ezpublish_legacy/settings/siteaccess/site/site.ini.append.php
sed -i "s|Password=.*|Password=$PASSWORD|" $CONF

CONF=/var/www/ezpublish/ezpublish_legacy/settings/siteaccess/site_admin/site.ini.append.php
sed -i "s|Password=.*|Password=$PASSWORD|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=ezpublish --pass="$PASSWORD"

