#!/bin/bash -e

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF="/var/www/ezplatform/.env"
sed -i "s|APP_SECRET=.*|APP_SECRET=$PASSWORD|" $CONF
sed -i "s|DATABASE_PASSWORD=.*|DATABASE_PASSWORD=$PASSWORD|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=ezplatform --pass="$PASSWORD"

