#!/bin/bash -e
# set ez platform admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/ezplatform.py --pass="$APP_PASS" --email="$APP_EMAIL"
